type = "service_account"
project_id = "rising-amp-379110"
private_key_id = "e794d0e0ad61b95bf88758d6c21d7a3bc96bf587"

# Use triple quotes to store the multi-line private key
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDO4xG2ePJLYpTQ
QJr+FqKKnn9lwG7cNQMlyzxzFPD2XTeAhN10xBTfbCxW6KwQkfkAr2F5zDo50tIT
34Ga2IIvb3ceGuXuSDyrO+fefJu5xNEUPYMOKhGQDX/qGI5hvLBn9teMwln79ghO
YtsLDRptzVB8Ki/eHelGsw6klf/d4aPn5mC9/RTueCo7X2IzrgDcBv+uvugZaCvU
HFdOkqeXAeiAkHxufFGaCM09R2REfEJpXhgKkXjCdJToQUmPLjnQeKcD3Mzy7yYH
h992bkKdWnP0wCD5xc5CPIurLux/ZJL7pmNQPAY5xlif+SYk9E7sabcvs7VAySKv
VNvQWRHtAgMBAAECggEAEN8vVGk11HRpD56x+FZSOFAt5Yqbv9uW5ey85+NL6PUe
XJ3GDaRPOEIMtgqD71bOlRuFLVCjAvb9aN98voSfmuZR//BQbG4TSVRsvi+W54x0
dikaC5XeS5gkpJIO5bH+O0xD6D4rs0LHCwimzzAcLEFmw4MRPXteldE7OKx+6rih
ViW+Kek8UcUQG4NtjXXTOYl9dxLVMG/akHxFY92f0M4R+X04/3csMLnMOvr5YqDw
g9qrHDm5Z4CAEkUhRfU7DcUthvReMAlqFPz/a955k+85kmz/GG6imkPokS40L3UK
q2E8kpDjZ5DsT9d7WYr/+BSIiG8fvs6kX5IhUyMAhQKBgQD9eCpLDY8+95eBQX0p
VWm2azOuuyoYCzInY6Eev92T6p5cWrm2ZfobATWLLUufYVJzhGWT2+ZQBGIvrqMx
qLe1w/qyAWzP73RmZP5CZpJbRW1CEZ02564Mw0ReUx3UHfGfdsCMguI8jjxGw01T
0uNTk9y68c1Uc63xdZb1bXAkcwKBgQDQ89htCO1LB1/xUtgt7IXDrxuJtpxqgbZP
OM/HItao2441BZWDFev2KxlkwuoAEizAeig+kj0umqGdOF9DLWpPhd24ppKS9LAw
OcniOYHXkyEcscOITFnEsNiP9qHlHc4WSHatg2RdgJs2vHbdc3kvY5ADC4RoKWhn
9rUNoaa4HwKBgQDzg6YGUzGjChX5bWSE+HVGd3nAzjojvWXi59ncg/Kp8EdSbSts
rE578U5ytwKnTcX8C1/XjPWZPIzkSICq7fAJZg6NQ8c5glEvKqoIOykzHOFaDzge
jrjttBAUGwBWUKpZTKqyk/Asw23vgiTheoNCQZVX2YUuNLERgKqWghyyNwKBgBMu
Ty+zIhVBGA2PDUkp7R2JdX2uxa0BOzsKfAhLqmjVvrgfSxo9aOuwCSS2v8RB5tnE
XO1hfzxH9Y35HsWL5bZnE3Nf1xSmYYYLx/x8Su7/EosPxmM8nwDvOvH8MeBWXBSv
kjVbWls68wSTSFYLw5QWD6I37G+jXXIts3EM5cEBAoGABXn0+KAT3HtNGX0YgCRv
1MRoXNI3XKw5DSMDU54VJ0Fl2oJCosLXwWDrlXCZBT8G3Qf6wNl88iJp+INnyphj
SvfPnDrGjarMM3BiqGwTeSR2iWVPhFQNpZIAdMHo+Df/YQawEEuUXe7gEC0UNOEA
fS/OQjhy59JPJ/dNLWl6zo0=
-----END PRIVATE KEY-----
"""

client_email = "mohammedesam06-gmail-com-96@rising-amp-379110.iam.gserviceaccount.com"
client_id = "118153265202546587418"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mohammedesam06-gmail-com-96%40rising-amp-379110.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
